### ISSUE TITLE
Implement the ever-growing part of the single page with exact theme

### ISSUE THREAD

**Issue by myquery** [Oreoswap-BSC/oreoswap-frontend-public#13]
**Descriptions**
The ever-growing section of the page should be implemented with the exact theme from the UI prototype. include asset needed to theme the section accordingly

**Features**

- Ensure responsive in all viewports
- Use mobile first approach
- Implement the switch mode (light and dark theme)

![oreswap-below-banner2](https://user-images.githubusercontent.com/349462/118562734-2da06b80-b765-11eb-880a-fe13f180df67.jpeg)

**Comment by InnoOkeke** [comment]
On it
