### ISSUE TITLE
Check the site responsive on all viewport

### ISSUE THREAD

**Issue by myquery** [Oreoswap-BSC/oreoswap-frontend-public#25]
**Descriptions.**
Go through the site and view it in different viewport to ascertain if it displays properly

**Features**
Target all viewport;m form the smallest mobile view to the largest desktop view

**Comment by Waleriagthub** [comment]
I have gone through the site on all viewports, from the smallest to desktop view. The responsiveness was okay.
My only concern is with the navigation bar in dark-mode view. We need to change the colour of the Oreo logo and text in dark mode.
