### ISSUE TITLE
Define CSS Color Theme

### ISSUE THREAD

**Issue by Rex739** [Oreoswap-BSC/oreoswap-frontend-public#33]
Store the colors from the [design](https://www.figma.com/file/pTCiZXlHTPitSqV7lAeGiV/OreoSwap-Redesign?node-id=2%3A140) as :root syntax in _color.css

![Screenshot_20210802-165646_Chrome.jpg](https://user-images.githubusercontent.com/54443717/127890208-3189e6bc-aae2-4a75-abcf-ff98b8ef7d6b.jpg)

**Comment by Abhijeet-Anand-01** [comment]
Hello! Can you assign me this task?
