### ISSUE TITLE
implement Hero section

### ISSUE THREAD

**Issue by Rex739** [Oreoswap-BSC/oreoswap-frontend-public#36]
![hero](https://user-images.githubusercontent.com/54443717/128172828-22b91958-a453-4208-9a54-db5f9f88bc64.jpg)
implement this section following the design precisely 

- apply both light and dark theme
- make sure its responsive on all mobile screens
- should be responsive on all desktop screens including higher than 4k screen resolution

**Comment by Abumuazu** [comment]
working on this too ...
