### ISSUE TITLE
Develop Stats section

### ISSUE THREAD

**Issue by Rex739** [Oreoswap-BSC/oreoswap-frontend-public#37]
![stats](https://user-images.githubusercontent.com/54443717/128174719-ef3d5cf5-1337-421e-bd11-c443606b09bd.jpg)
implement this section following design precisely 

- apply both light and dark theme
- make sure its responsive on all mobile screens
- should be responsive on all desktop screens including higher than 4k screen resolution
- [Glassmorphism](https://glassmorphism.com/)  principle was used as background

**Comment by Abumuazu** [comment]
Working on this now ....
