### ISSUE TITLE
Implement Community Section

### ISSUE THREAD

**Issue by Rex739** [Oreoswap-BSC/oreoswap-frontend-public#40]
![community](https://user-images.githubusercontent.com/54443717/128182662-0aeda86a-f0f4-4340-aefd-bbaabdef932a.jpg)
implement this section following the design precisely

- apply both light and dark theme
- make sure its responsive on all mobile screens
- should be responsive on all desktop screens including higher than 4k screen resolution

**Comment by Abumuazu** [comment]
hi guys, sorry I have been offshore. I would start with this...
