### ISSUE TITLE
Implement Footer Section

### ISSUE THREAD

**Issue by Rex739** [Oreoswap-BSC/oreoswap-frontend-public#41]
![footer](https://user-images.githubusercontent.com/54443717/128182901-5e8b92b8-8bca-47d7-8d02-b0796a0734bf.jpg)
implement this section following the design precisely

- apply both light and dark theme
- make sure its responsive on all mobile screens
- should be responsive on all desktop screens including higher than 4k screen resolution

**Comment by ekomic** [comment]
am working on this, @ Chris Ekom
