### ISSUE TITLE
Implement the banner for oreowap.com

### ISSUE THREAD

**Issue by myquery** [Oreoswap-BSC/oreoswap-frontend-public#5]
**Descriptions**
Implement the banner for the landing page with exact theme

![image](https://user-images.githubusercontent.com/349462/118282151-e2b4f880-b4c5-11eb-8e33-9ea1acb98b48.png)

#### Feature

- Each feature should be component
- Locate the component folder at the src folder to add your component

**Comment by Rex739** [comment]
i'll take this
